version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 510001482086.dkr.ecr.us-east-1.amazonaws.com)

  build:
    commands:
      - echo Building Docker image...
      - docker build -t simple-web-app .
      - docker tag simple-web-app:latest 510001482086.dkr.ecr.us-east-1.amazonaws.com/simple-web-app:latest

  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push 510001482086.dkr.ecr.us-east-1.amazonaws.com/simple-web-app:latest

      #  This must match the ECS container name
      - echo Creating imagedefinitions.json for ECS deploy...
      - printf '[{"name":"weather-container","imageUri":"%s"}]' 510001482086.dkr.ecr.us-east-1.amazonaws.com/simple-web-app:latest > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json

