name: CI/CD Pipeline - Flask App

on: 
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/weather-app:${{ github.run_number }} .

    - name: Run Docker container
      run: |
        docker stop weather-app-container || true
        docker rm weather-app-container || true
        docker run -d -p 8080:8080 --name weather-app-container ${{ secrets.DOCKER_USERNAME }}/weather-app:${{ github.run_number }}

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Tag Docker image as latest
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/weather-app:${{ github.run_number }} ${{ secrets.DOCKER_USERNAME }}/weather-app:latest

    - name: Push Docker image to DockerHub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/weather-app:${{ github.run_number }}
        docker push ${{ secrets.DOCKER_USERNAME }}/weather-app:latest
