name: CI/CD Pipeline - Flask App

# on:
#   push:
#     branches: [ "main" ]

on: 
  workflow_dispatch:
  
jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # - name: Set up Python
    #   uses: actions/setup-python@v4
    #   with:
    #     python-version: 3.11

    # - name: Install dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install -r requirements.txt
    
    # - name: Test Python app
    #   run: |
    #     echo "🧪 Add tests here if needed"

    - name: Building docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/devops:${{ github.run_number }} .
    
    - name: Run Docker Container
      run: |
        docker run -d -p 8080:8080 --name ${{ secrets.DOCKER_USERNAME }}/devops:${{ github.run_number }}

    # - name: Build & Push Docker image
    #   uses: mr-smithers-excellent/docker-build-push@v6
    #   with:
    #     image: <your-dockerhub-username>/weather-app
    #     registry: docker.io
    #     tags: latest
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}

